export const ERROR_CODES = {
  COMMON_UNKNOWN: 'COMMON_UNKNOWN',
  COMMON_VALIDATION: 'COMMON_VALIDATION',
  COMMON_NOT_IMPLEMENTED: 'COMMON_NOT_IMPLEMENTED',
  COMMON_UNAUTHORIZED: 'COMMON_UNAUTHORIZED',
  BASE_DATA_API_SHAPE_MISMATCH: 'BASE_DATA_API_SHAPE_MISMATCH',

  AUTH_SIGN_UP_FAILED: 'AUTH_SIGN_UP_FAILED',
  AUTH_SIGN_IN_FAILED: 'AUTH_SIGN_IN_FAILED',
  AUTH_SIGN_OUT_FAILED: 'AUTH_SIGN_OUT_FAILED',
  AUTH_DUPLICATE_EMAIL_POSSIBLE: 'AUTH_DUPLICATE_EMAIL_POSSIBLE',

  TRIP_FETCH_FAILED: 'TRIP_FETCH_FAILED',
  TRIP_CREATE_FAILED: 'TRIP_CREATE_FAILED',

  PREFERENCE_FETCH_FAILED: 'PREFERENCE_FETCH_FAILED',
  PREFERENCE_UPSERT_FAILED: 'PREFERENCE_UPSERT_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export type ErrorSource = 'frontend' | 'backend' | 'supabase' | 'unknown';

export interface AppError {
  code: ErrorCode;
  source: ErrorSource;
  message?: string;
  details?: string;
}
